-- insight.TB_BOARD definition

CREATE TABLE `TB_BOARD` (
  `BOARD_IDX` int NOT NULL AUTO_INCREMENT COMMENT '글 번호',
  `TITLE` varchar(300) NOT NULL COMMENT '제목',
  `CONTENTS` text NOT NULL COMMENT '내용',
  `HIT_CNT` smallint NOT NULL DEFAULT '0' COMMENT '조회수',
  `CREATED_DATETIME` datetime NOT NULL COMMENT '작성시간',
  `CREATOR_ID` varchar(50) NOT NULL COMMENT '작성자',
  `UPDATED_DATETIME` datetime DEFAULT NULL COMMENT '수정시간',
  `UPDATER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '수정자',
  `DELETED_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`BOARD_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;